### ISSUE TITLE
docker: no matching manifest for linux/amd64 in the manifest list entries.

### ISSUE THREAD

**Issue by logdns** [tmplink/nsfw_detector#2]
Unable to find image 'vxlink/nsfw_detector:latest' locally
latest: Pulling from vxlink/nsfw_detector
docker: no matching manifest for linux/amd64 in the manifest list entries.

**Comment by logdns** [comment]
Ubuntu SMP Tue Aug 13 09:07:08 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by logdns** [comment]
Pulling from vxlink/nsfw_detector
bt_failed, !{'message': 'no matching manifest for linux/amd64 in the manifest list entries'}



docker run -d -p 3333:3333 --name nsfw-detector vxlink/nsfw_detector:latest
Unable to find image 'vxlink/nsfw_detector:latest' locally
latest: Pulling from vxlink/nsfw_detector
docker: no matching manifest for linux/amd64 in the manifest list entries.
See 'docker run --help'.

**Comment by tmplink** [comment]
We have updated the image to include image packages for the amd64 architecture. Please try and see if you can complete the deployment.

**Comment by logdns** [comment]
ok
